fail_fast: false
files: '^.*\.py$'
default_language_version:
  python: python3.10
repos:
  - repo: local
    hooks:
      - id: isort
        name: check-imports
        entry: isort src/ tests/
        language: system
        types: [python]

      - id: black
        name: format-style
        entry: black src/ tests/
        language: system
        types: [python]

      - id: pyright
        name: check-typing
        entry: pyright src/ tests/
        language: system
        types: [python]
        pass_filenames: false

      - id: ruff
        name: linter
        entry: ruff src/ tests/
        language: system
        types: [python]
