fail_fast: true
files: '^.*\.py$'
default_language_version:
  python: python3.11
repos:
  - repo: local
    hooks:
      - id: isort
        name: check-imports
        entry: isort src/ tests/
        language: system
        types: [python]

      - id: black
        name: format-style
        entry: black src/ tests/
        language: system
        types: [python]

      - id: pyright
        name: check-typing
        entry: pyright src/ tests/
        language: system
        types: [python]
        pass_filenames: false

      - id: ruff
        name: linter
        entry: ruff --fix src/ tests/
        language: system
        types: [python]

      - id: pytest
        name: unit-tests
        entry: pytest tests/ --tb=short
        language: system
        types: [python]
