fail_fast: false
files: '^.*\.py$'
default_language_version:
  python: python3.10
repos:
  - repo: local
    hooks:
      - id: isort
        name: check-imports
        entry: isort .
        language: system
        types: [python]

      - id: black
        name: format-style
        entry: black .
        language: system
        types: [python]

      - id: mypy
        name: check-typing
        entry: mypy .
        language: system
        types: [python]
        pass_filenames: false

      - id: ruff
        name: linter
        entry: ruff .
        language: system
        types: [python]
